backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/media" # Media files will be stored in the repo under images/uploads
public_folder: "/media"

collections:
  - label: "Test"
    name: "test"
    folder: "_content/test"
    create: true
    identifier_field: test
    fields:
      - {label: "Test", name: "test", widget: "string"}